version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: morphos_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/danvergara/morphos-server:0.2.0
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8080:8080
    volumes:
      - ${APP_DATA_DIR}/tmp:/tmp
